name: CD - Deploy to dev

on:
  push:
    branches:
      - feauture-dev-i

permissions:
  contents: read
  id-token: write
  
jobs:
  deploy-dev:
    uses: ops-migration/central-shared-workflow/.github/workflows/cd-workflow.yml@main
    with:
      cf-stack-name: "dev-stack"
